services:
  jenkins-controller:
    image: jenkins/jenkins:lts
    container_name: jenkins-controller
    ports:
      - "8080:8080"      # Jenkins Web UI
      - "50000:50000"    # JNLP (на будущее)
    volumes:
      - jenkins_home:/var/jenkins_home
    networks: [jenkins-network]

  ssh-agent:
    build:
      context: .
      dockerfile: Dockerfile.ssh_agent
    container_name: ssh-agent
    user: root
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    volumes:
      - jenkins_agent_volume:/home/jenkins/agent
    depends_on: [jenkins-controller]
    networks: [jenkins-network]

  ansible-agent:
    build:
      context: .
      dockerfile: Dockerfile.ansible_agent
    container_name: ansible-agent
    environment:
      - JENKINS_ANSIBLE_AGENT_SSH_PUBKEY=${JENKINS_ANSIBLE_AGENT_SSH_PUBKEY}
      - ANSIBLE_HOST_KEY_CHECKING=False
    volumes:
      - ansible_agent_volume:/home/jenkins/agent
      # Приватный ключ для подключения к тест-серверу (только чтение)
      - ./secrets/test_server_ansible_key:/home/jenkins/.ssh/test_server_ansible_key:ro
      # Рабочая папка с Ansible (плейбуки/инвентори)
      - ./ansible:/opt/ansible
    depends_on: [jenkins-controller, test-server]
    networks: [jenkins-network]

  test-server:
    build:
      context: .
      dockerfile: Dockerfile.test_server
    container_name: test-server
    # Откроем 80 наружу, чтобы проверить сайт в браузере
    ports:
      - "8088:80"
    networks: [jenkins-network]

volumes:
  jenkins_home:
  jenkins_agent_volume:
  ansible_agent_volume:

networks:
  jenkins-network:
    driver: bridge