FROM jenkins/ssh-agent

USER root

# Устанавливаем PHP + нужные расширения
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    php-cli \
    php-xml \
    php-mbstring \
    git \
    unzip \
    curl \
    ca-certificates \
    && curl -sS https://getcomposer.org/installer \
    | php -- --install-dir=/usr/local/bin --filename=composer \
    && rm -rf /var/lib/apt/lists/*

USER jenkins